export const STATIC_FOOD_DATA = [
    { id: "sf1", name: "English Muffin Breakfast Pizza", servingSize: 1, servingUnit: "serving", image: "" },
    { id: "sf2", name: "Strawberry, Spinach, Cucumber Smoothie", servingSize: 1, servingUnit: "serving", image: "" },
    { id: "sf3", name: "Salmon & Potato Scramble", servingSize: 1, servingUnit: "serving", image: "" },
    { id: "sf4", name: "Vanilla, Banana, and Kale Protein Smoothie", servingSize: 1, servingUnit: "serving", image: "" },
    { id: "sf5", name: "Soft Scrambled Eggs with Goat Cheese and Asparagus", servingSize: 1, servingUnit: "serving", image: "" },
    { id: "sf6", name: "Ham and Veggie Omelet", servingSize: 1, servingUnit: "serving", image: "" },
    { id: "sf7", name: "Orange Dream Protein Smoothie", servingSize: 1, servingUnit: "serving", image: "" },
    { id: "sf8", name: "Spinach Frittata with Sweet Potato Crust", servingSize: 1, servingUnit: "serving", image: "" },
    { id: "sf9", name: "Berry and Spinach Smoothie", servingSize: 1, servingUnit: "serving", image: "" },
    { id: "sf10", name: "Almonds and Blueberries Yogurt Snack", servingSize: 1, servingUnit: "serving", image: "" },
    { id: "sf11", name: "Chocolate Oats", servingSize: 1, servingUnit: "serving", image: "" },
    { id: "sf12", name: "Soft Boiled Eggs & Toast", servingSize: 1, servingUnit: "serving", image: "" },
    { id: "sf13", name: "Ham and Egg Scramble", servingSize: 1, servingUnit: "serving", image: "" },
    { id: "sf14", name: "Protein Silver Dollar Blueberry Pancakes", servingSize: 1, servingUnit: "serving", image: "" },
    { id: "sf15", name: "Skinny Greek Omelet", servingSize: 1, servingUnit: "serving", image: "" },
    { id: "sf16", name: "Poached Eggs in Spinach", servingSize: 1, servingUnit: "serving", image: "" },
    { id: "sf17", name: "Basic Parmesan Egg White Omelet", servingSize: 1, servingUnit: "serving", image: "" },
    { id: "sf18", name: "Yogurt & Pineapple", servingSize: 1, servingUnit: "serving", image: "" },
    { id: "sf19", name: "Blueberry Muffin Overnight Oats", servingSize: 1, servingUnit: "serving", image: "" },
    { id: "sf20", name: "Mushroom Spinach Omelet Recipe", servingSize: 1, servingUnit: "serving", image: "" },
    { id: "sf21", name: "Basic scrambled eggs", servingSize: 1, servingUnit: "serving", image: "" },
    { id: "sf22", name: "Healthy Avocado Egg Salad and Salmon Sandwich", servingSize: 1, servingUnit: "serving", image: "" }
];

export const FEATURED_COLLECTIONS = [
    { title: "High Protein Breakfast Ideas", description: "Start your day with these protein-packed meals.", creator: "Nutritionist Team", itemCount: 12 },
    { title: "Pantry & Freezer Recipes", description: "Easy meals using what you already have.", creator: "Kitchen Hackers", itemCount: 15 },
    { title: "Slow Cooker Dinners", description: "Set it and forget it for busy weeknights.", creator: "Home Chef", itemCount: 20 },
    { title: "Quick Lunch Recipes", description: "Healthy lunches ready in 15 minutes.", creator: "Speedy Eats", itemCount: 10 },
    { title: "Fruits & nuts", description: "Refreshing snack ideas for healthy energy.", creator: "Wellness Hub", itemCount: 8 },
    { title: "Veggies", description: "Making vegetables the star of your plate.", creator: "Green Garden", itemCount: 14 },
    { title: "Sandwiches & Wraps", description: "Classic and creative handheld meals.", creator: "Lunch Box", itemCount: 11 },
    { title: "Shakes & Smoothies", description: "Drinkable nutrition for on-the-go.", creator: "Smoothie King", itemCount: 22 },
    { title: "Not-Too-Sweet Treats", description: "Healthier desserts that satisfy cravings.", creator: "Sugar Free", itemCount: 9 },
    { title: "Trader Joe's Frozen Entrees", description: "Hack the frozen section for easy meals.", creator: "TJ Enthusiast", itemCount: 18 },
    { title: "Vegetarian Indian Meals", description: "Spiced and aromatic vegetarian delights.", creator: "Desi Flavors", itemCount: 16 },
    { title: "Air Fryer Meals", description: "Crispy textures with less oil.", creator: "Tech Chef", itemCount: 13 },
    { title: "Hearty Soups & Stews", description: "Warm and comforting liquid meals.", creator: "Winter Cozy", itemCount: 19 },
    { title: "Omelettes & Quiches", description: "The ultimate egg-based breakfast guide.", creator: "Egg Specialist", itemCount: 14 },
    { title: "Casseroles", description: "One-dish meals for the whole family.", creator: "Family Table", itemCount: 15 },
    { title: "Spicy Dinner Ideas", description: "Turn up the heat with these fiery recipes.", creator: "Chili Head", itemCount: 11 },
    { title: "Hearty Dinner Salads", description: "Filling salads that eat like a meal.", creator: "Salad Bar", itemCount: 16 },
    { title: "Asian-inspired Vegetarian Meals", description: "Plant-based twists on classic Asian flavors.", creator: "Wok Star", itemCount: 17 },
    { title: "Vegetarian Dinners", description: "Satisfying meatless main courses.", creator: "Plant Powered", itemCount: 20 },
    { title: "Tofu Recipes", description: "Mastering the world's most versatile protein.", creator: "Tofu Master", itemCount: 12 },
    { title: "Quinoa Dishes", description: "Healthy grains for any meal.", creator: "Grain Guru", itemCount: 10 },
    { title: "Chicken Recipes", description: "New ways to prep your favorite bird.", creator: "Protein Plus", itemCount: 25 },
    { title: "Southwestern/Mexican Vegetarian Meals", description: "Bold spices and meatless tacos.", creator: "Fiesta Plate", itemCount: 18 },
    { title: "Salmon Dishes", description: "Heart-healthy and delicious seafood.", creator: "Omega Expert", itemCount: 14 },
    { title: "Seafood Recipes", description: "Fresh from the ocean to your table.", creator: "Coastal Eats", itemCount: 16 },
    { title: "Trader Joe's Breakfasts", description: "Speedy morning hacks from TJs.", creator: "TJ Enthusiast", itemCount: 12 },
    { title: "Razi's Recipes", description: "Curated selections from Razi.", creator: "Razi", itemCount: 30 },
    { title: "Nonperishable ingredients recipes", description: "Long-lasting meals for any time.", creator: "Survival Chef", itemCount: 14 },
    { title: "Trader Joe's Fresh Meals", description: "Healthy fresh picks from TJs.", creator: "TJ Enthusiast", itemCount: 15 },
    { title: "Trader Joe's Microwave Meals", description: "Heat and eat favorites.", creator: "TJ Enthusiast", itemCount: 11 },
    { title: "Cakes and Pies", description: "The sweeter side of life.", creator: "Bake Shop", itemCount: 13 },
    { title: "Autumn Recipes", description: "Fall flavors like pumpkin and sage.", creator: "Seasonal Eats", itemCount: 21 },
    { title: "Overnight Oats & Porridge", description: "Ready when you wake up.", creator: "Morning Prep", itemCount: 16 },
    { title: "Mexican", description: "Authentic and adapted Mexican classics.", creator: "Salsa Specialist", itemCount: 24 }
].map((c, i) => ({ ...c, id: `fc${i + 1}`, isFeatured: true, createdAt: new Date().toISOString() }));
